$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: vllm-aml-mixtral-deployment
endpoint_name: nim-aml-endpoint-1
# azureml model is loaded but not used
model: azureml://registries/azureml/models/mistralai-Mixtral-8x7B-Instruct-v01/versions/5
environment: azureml://registries/NVIDIARegistryTest1/environments/nim-off-env/versions/1 
instance_type: Standard_NC96ads_A100_v4
instance_count: 1
request_settings:
  max_concurrent_requests_per_instance: 15
  request_timeout_ms: 10000
environment_variables:
    MODEL_SUBDIR: "mlflow_model_folder/data/model"
    MODEL_HF_NAME: "mistralai/Mixtral-8x7B-Instruct-v0.1"
    NUM_GPUS: "4"
